language: python

python:
    - "2.7"

before_install:
    - pip install pytest

install:
    - python setup.py install
script:
    - py.test tests/unit.py
notifications:
    email:
        - vidyac.raghav@gmail.com
        - vidya_test1@yahoo.in
